// Generated by tools/generate_i_decoder.py from compiler/isa_spec.py — DO NOT EDIT

module i_decoder (
    input  logic [63:0] instr,
    output logic [4:0]  opcode,
    output logic [4:0] dest,
    output logic [17:0] length_or_cols,
    output logic [9:0] rows,
    output logic [23:0] addr,
    output logic [4:0] b,
    output logic [4:0] x,
    output logic [4:0] w,
    output logic [5:0] fmap_h,
    output logic [5:0] fmap_w,
    output logic [5:0] in_channels,
    output logic [5:0] out_channels,
    output logic [3:0] kernel_h,
    output logic [3:0] kernel_w,
    output logic [2:0] stride_val,
    output logic [2:0] pad_val,
    output logic [2:0] pool_size,
    output logic        relu_flag
);

    always_comb begin
        opcode = instr[4:0];

        // Defaults — every output deassserted unless an opcode case drives it
        dest = 0;
        length_or_cols = 0;
        rows = 0;
        addr = 0;
        b = 0;
        x = 0;
        w = 0;
        fmap_h = 0;
        fmap_w = 0;
        in_channels = 0;
        out_channels = 0;
        kernel_h = 0;
        kernel_w = 0;
        stride_val = 0;
        pad_val = 0;
        pool_size = 0;
        relu_flag = 0;

        case (opcode)
            5'h00: begin // NOP
            end

            5'h01: begin // LOAD_V — Load vector from DRAM into a vector buffer
                addr = instr[63:40];
                length_or_cols = instr[27:10];
                dest = instr[9:5];
            end

            5'h02: begin // LOAD_M — Load matrix from DRAM into a matrix buffer (cols padded to TILE_ELEMS)
                addr = instr[63:40];
                rows = instr[29:20];
                length_or_cols = {8'b0, instr[19:10]};
                dest = instr[9:5];
            end

            5'h03: begin // STORE — Write a vector buffer back to DRAM
                addr = instr[63:40];
                length_or_cols = instr[27:10];
                dest = instr[9:5];
            end

            5'h04: begin // GEMV — dest = quant(W*x + b), int32 accumulator, per-tensor max-abs scale
                w = instr[44:40];
                x = instr[39:35];
                b = instr[34:30];
                rows = instr[29:20];
                length_or_cols = {8'b0, instr[19:10]};
                dest = instr[9:5];
            end

            5'h05: begin // RELU — Element-wise max(0, x); FC outputs only (10-bit length)
                length_or_cols = {8'b0, instr[29:20]};
                x = instr[14:10];
                dest = instr[9:5];
            end

            5'h06: begin // CONV2D_CFG — Latch convolution geometry; precedes CONV2D_RUN
                pad_val = instr[47:45];
                stride_val = instr[44:42];
                kernel_w = instr[41:38];
                kernel_h = instr[37:34];
                out_channels = instr[33:28];
                in_channels = instr[27:22];
                fmap_w = instr[21:16];
                fmap_h = instr[15:10];
                dest = instr[9:5];
            end

            5'h07: begin // CONV2D_RUN — Execute conv2d using last CONV2D_CFG; relu_flag fuses ReLU
                relu_flag = instr[25];
                b = instr[24:20];
                w = instr[19:15];
                x = instr[14:10];
                dest = instr[9:5];
            end

            5'h08: begin // MAXPOOL — Sliding-window NCHW max-pool; operates on int8 directly
                in_channels = {1'b0, instr[37:33]};
                fmap_w = instr[32:27];
                fmap_h = instr[26:21];
                stride_val = instr[20:18];
                pool_size = instr[17:15];
                x = instr[14:10];
                dest = instr[9:5];
            end

            default: begin
            end
        endcase
    end
endmodule
