"""Generate rtl/accelerator_config_pkg.sv from the SimProfile in compiler/accelerator_config.py.

Pre-P3 this file generated BOTH the RTL package and `compiler/accelerator_config.py`.
Post-P3 the Python config is hand-edited (it carries two named profiles — `sim`
and `fpga` — selected at runtime via the `TINYML_PROFILE` env var) and this
generator only emits the RTL package, sourcing parameters from `SimProfile`.

The simulation RTL (`rtl/tinyml_accelerator_top.sv`) `import`s the generated
package; FPGA-tier RTL (`src/tinyml_accelerator_top_fpga.sv`,
`test/heavy_test_fpga/tinyml_accelerator_top.sv`) hard-codes its own
parameters and does not use this package.
"""
import os
import sys

# Allow running this script from the repo root without installing the compiler dir.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "compiler"))

from accelerator_config import SimProfile  # noqa: E402


def generate_rtl_package(cfg=SimProfile, output_path="rtl/accelerator_config_pkg.sv"):
    content = f"""// Generated by generate_config.py from compiler/accelerator_config.py::SimProfile
// DO NOT EDIT DIRECTLY — edit SimProfile and re-run.

package accelerator_config_pkg;

    // Data and Address Widths
    parameter DATA_WIDTH = {cfg.DATA_WIDTH};
    parameter ADDR_WIDTH = {cfg.ADDR_WIDTH};

    // Tiling
    parameter TILE_ELEMS = {cfg.TILE_ELEMS};
    parameter TILE_WIDTH = {cfg.TILE_WIDTH}; // TILE_ELEMS * DATA_WIDTH

    // Buffer Sizes (bits)
    parameter VECTOR_BUFFER_WIDTH = {cfg.VECTOR_BUFFER_WIDTH};
    parameter MATRIX_BUFFER_WIDTH = {cfg.MATRIX_BUFFER_WIDTH};

    // Architecture Limits
    parameter MAX_ROWS = {cfg.MAX_ROWS};
    parameter MAX_COLS = {cfg.MAX_COLS};
    parameter OUT_N    = {cfg.OUT_N};

endpackage
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Generated {output_path} from SimProfile")


def main():
    generate_rtl_package()


if __name__ == "__main__":
    main()
