#!/usr/bin/env python3
"""Join frozen full-set oracle logits with verified inputs and current layout.

Reuse the independent oracle already generated by prepare_smallcnn.py
--jobs 10000 --quality-only; do not relabel an incompatible model's results.
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

import numpy as np

from run_models import ROOT, digest, load_fixture
sys.path.insert(0, str(ROOT / 'compiler'))
sys.path.insert(0, str(ROOT / 'tools/phase3'))
from prepare_smallcnn import idx, float_input
from program_image import load_image
from integer_reference import evaluate


def prepare(fixture, oracle, output):
    meta, image, existing = load_fixture(fixture, 1)
    old = json.loads((oracle / 'board.json').read_text())
    for name in ('software.uq2', 'calibration.json', 'source.onnx', 'board.bin'):
        if digest(fixture / name) != digest(oracle / name):
            raise ValueError(f'full-set oracle differs: {name}')
    for key in ('weights_sha256', 'source_sha256', 'dataset_sha256', 'calibration_ids'):
        if meta[key] != old[key]:
            raise ValueError(f'full-set provenance differs: {key}')
    raw = ROOT / 'compiler/data/MNIST/raw'
    for name, expected in meta['dataset_sha256'].items():
        if digest(raw / name) != expected:
            raise ValueError(f'MNIST digest mismatch: {name}')
    samples = idx(raw / 't10k-images-idx3-ubyte')
    labels = idx(raw / 't10k-labels-idx1-ubyte')
    if len(samples) != 10000 or len(labels) != 10000:
        raise ValueError('full MNIST test set required')
    program = load_image((fixture / 'software.uq2').read_bytes())
    quantizer = program.tensors['input'].quantization
    inputs = np.array([quantizer.encode(float_input(x)) for x in samples])
    with np.load(oracle / 'quality-predictions.npz', allow_pickle=False) as saved:
        outputs = saved['outputs']
        np.testing.assert_array_equal(labels, saved['labels'])
    if outputs.dtype != np.int8 or outputs.shape != (10000, 1, 10):
        raise ValueError('invalid oracle shape/type')
    for key, values in (('inputs', inputs), ('outputs', outputs), ('labels', labels)):
        np.testing.assert_array_equal(values[:len(existing[key])], existing[key])
    # Independently recheck the beginning, middle and end of the cached oracle.
    for index in (0, 5000, 9999):
        result = evaluate(program, {'input': inputs[index]})
        np.testing.assert_array_equal(result[program.outputs[0]], outputs[index])
    correct = int(np.sum(outputs.reshape(10000, -1).argmax(1) == labels))
    if correct != old['integer_correct']:
        raise ValueError('cached quality count differs')
    output.mkdir(parents=True, exist_ok=True)
    for name in ('board.bin', 'software.uq2', 'calibration.json', 'source.onnx'):
        shutil.copyfile(fixture / name, output / name)
    np.savez_compressed(output / 'checks.npz', inputs=inputs, outputs=outputs, labels=labels)
    meta.update(jobs=10000, integer_correct=correct,
                oracle_predictions_sha256=digest(oracle / 'quality-predictions.npz'),
                oracle_metadata_sha256=digest(oracle / 'board.json'),
                oracle_spot_checks=[0, 5000, 9999])
    (output / 'board.json').write_text(json.dumps(meta, indent=2) + '\n')
    load_fixture(output, 10000)
    print(f'Prepared 10,000 verified SmallCNN cases; oracle correct: {correct}')


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--fixture', type=Path, default=ROOT / 'work/phase3/smallcnn')
    p.add_argument('--oracle', type=Path, default=ROOT / 'work/phase3/full-quality')
    p.add_argument('--output', type=Path, default=ROOT / 'work/physical/smallcnn-full')
    a = p.parse_args()
    prepare(a.fixture, a.oracle, a.output)
