"""Accelerator configuration — single source of truth for both Python and RTL.

Two named profiles live here, selected at import time by the
`TINYML_PROFILE` environment variable:

    sim   (default) — Verilator/cocotb simulation; TILE_ELEMS=32, 60 KB DRAM.
    fpga             — FPGA-tier simulation/synthesis; TILE_ELEMS=8, 32 KB DRAM.

Set the env var BEFORE any compiler module is imported (e.g. from a Makefile
or at the very top of a test script before `from accelerator_config import ...`).
After P3 (2026-05-08) this replaces the previous dual files
(`compiler/accelerator_config.py` auto-generated by `generate_config.py`,
plus `test/heavy_test_fpga/accelerator_config.py` overriding via sys.path).

The active profile is exposed under the historical name `AcceleratorConfig`,
so existing call sites that do `from accelerator_config import AcceleratorConfig`
keep working without edits. The two profile classes are also importable by
name (`SimProfile`, `FpgaProfile`) when callers need a specific one.

`generate_config.py` reads `SimProfile` to emit `rtl/accelerator_config_pkg.sv`;
the FPGA-tier RTL parameters are hard-coded in
`test/heavy_test_fpga/tinyml_accelerator_top.sv` and `src/tinyml_accelerator_top_fpga.sv`.
"""
import os


class SimProfile:
    """Verilator/cocotb simulation profile (TILE_ELEMS=32, 60 KB DRAM).

    Matches the parameters in `rtl/tinyml_accelerator_top.sv` and the
    `rtl/accelerator_config_pkg.sv` package generated from this profile.
    """
    DATA_WIDTH = 8
    ADDR_WIDTH = 16

    TILE_ELEMS = 32
    TILE_WIDTH = 256                      # TILE_ELEMS * DATA_WIDTH

    MEM_SIZE   = 0xF000                   # 60 KB

    VECTOR_BUFFER_WIDTH = 32768           # 4 KB per vector buffer (Patch J)
    MATRIX_BUFFER_WIDTH = 131072          # 16 KB per matrix buffer

    MAX_ROWS = 1024
    MAX_COLS = 1024
    OUT_N    = 10

    # Memory map (byte offsets into unified DRAM)
    DRAM_ADDR_INPUTS       = 0x00C0       # 192
    DRAM_ADDR_BIASES       = 0x04C0       # 1216  — all biases, topo order
    DRAM_ADDR_OUTPUTS      = 0x08C0       # 2240  — inference results
    DRAM_ADDR_WEIGHTS      = 0x0940       # 2368  — FC / Gemm weights, padded to TILE_ELEMS
    DRAM_ADDR_CONV_WEIGHTS = 0x3000       # 12288 — Conv weights, well after FC region


class FpgaProfile:
    """FPGA-tier profile (TILE_ELEMS=8, 32 KB DRAM, ADDR_WIDTH=15).

    Matches parameters in `test/heavy_test_fpga/tinyml_accelerator_top.sv`
    and `src/tinyml_accelerator_top_fpga.sv` (Tang Nano 20K target).

    With TILE_ELEMS=8 the MLP weight layout is:
        fc1 (12×784): 784 % 8 == 0 → no padding;          12 × 784 = 9408 B
        fc2 (32×12):  12 → padded to 16;                  32 × 16  =  512 B
        fc3 (10×32):  32 % 8 == 0 → no padding;           10 × 32  =  320 B
        Total weights ≈ 10 240 B → max addr 0x0940+10240 ≈ 0x3140 < 0x8000 (2^15).

    For SmallCNN on FPGA the conv weights (≤ ~400 B) sit at DRAM_ADDR_CONV_WEIGHTS;
    that region overlaps the FC weights window logically but never coexists with
    a fully-loaded MLP since the two networks aren't run from the same image.
    """
    DATA_WIDTH = 8
    ADDR_WIDTH = 15

    TILE_ELEMS = 8
    TILE_WIDTH = 64                       # TILE_ELEMS * DATA_WIDTH

    MEM_SIZE   = 32768                    # 32 KB

    VECTOR_BUFFER_WIDTH = 8192            # 1 KB per vector buffer (sufficient for MLP)
    MATRIX_BUFFER_WIDTH = 131072          # 16 KB — kept at sim size so fc1 (9408 B) fits

    MAX_ROWS = 784
    MAX_COLS = 784
    OUT_N    = 10

    # Memory map — kept identical to SimProfile so the same compiled instruction
    # stream addresses the same DRAM regions on both targets.
    DRAM_ADDR_INPUTS       = 0x00C0
    DRAM_ADDR_BIASES       = 0x04C0
    DRAM_ADDR_OUTPUTS      = 0x08C0
    DRAM_ADDR_WEIGHTS      = 0x0940
    DRAM_ADDR_CONV_WEIGHTS = 0x3000


PROFILES = {
    "sim":  SimProfile,
    "fpga": FpgaProfile,
}


def _select_profile():
    name = os.environ.get("TINYML_PROFILE", "sim").lower()
    if name not in PROFILES:
        raise ValueError(
            f"Unknown TINYML_PROFILE={name!r}; must be one of {list(PROFILES)}"
        )
    return PROFILES[name]


# The active profile, resolved once at import time. Tests/scripts that want to
# switch profiles must set the env var BEFORE the first compiler import (or
# call `set_profile(...)` and then re-import compiler modules — but the env-var
# pattern is strictly preferred since `dram.py` captures MEM_SIZE at module
# load and re-import is messy).
AcceleratorConfig = _select_profile()


def set_profile(name: str):
    """Switch the active profile. Best-effort: only safe BEFORE the first
    compiler module imports `AcceleratorConfig`, since consumers bind the
    name in their own module scope at import time.

    Prefer setting `TINYML_PROFILE` in the env / Makefile.
    """
    global AcceleratorConfig
    if name not in PROFILES:
        raise ValueError(f"Unknown profile: {name!r}; must be one of {list(PROFILES)}")
    AcceleratorConfig = PROFILES[name]


def active_profile_name() -> str:
    """Return 'sim' or 'fpga' for the currently-active profile."""
    for name, cls in PROFILES.items():
        if AcceleratorConfig is cls:
            return name
    return "?"  # shouldn't happen unless someone monkey-patched
