#!/usr/bin/env python3
"""Generate rtl/i_decoder.sv from compiler/isa_spec.py.

The RTL instruction decoder is a thin combinational case statement: every
opcode case picks a handful of bit ranges out of the 64-bit instruction
word and drives shared output ports (length_or_cols, rows, addr, etc.).
Hand-keeping it in sync with the assembler / disassembler / golden model
was the source of repeat bugs (e.g. Patch H bumped LOAD_V/STORE length
from 10→18 and had to touch four files at once). This generator removes
the manual sync.

Usage:
    python tools/generate_i_decoder.py            # writes rtl/i_decoder.sv
    python tools/generate_i_decoder.py --check    # exit non-zero if stale

Run via `make` after any edit to compiler/isa_spec.py.
"""
import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "compiler"))

import isa_spec  # noqa: E402

DEFAULT_OUTPUT = REPO_ROOT / "rtl" / "i_decoder.sv"
HEADER = "// Generated by tools/generate_i_decoder.py from compiler/isa_spec.py — DO NOT EDIT"


def _port_decl(name: str, width: int) -> str:
    if width == 1:
        return f"    output logic        {name}"
    return f"    output logic [{width - 1}:{0}] {name}"


def _emit_field_assignment(field: isa_spec.Field) -> str:
    """Return a single SystemVerilog assignment line for one field."""
    port_w = isa_spec.RTL_PORTS[field.port]
    if field.width == 1:
        # 1-bit fields use bit-select rather than range-select for cleaner SV
        return f"                {field.port} = instr[{field.lo}];"
    if field.width < port_w:
        pad = port_w - field.width
        return (f"                {field.port} = "
                f"{{{pad}'b0, instr[{field.hi}:{field.lo}]}};")
    return f"                {field.port} = instr[{field.hi}:{field.lo}];"


def render() -> str:
    lines = [HEADER, ""]
    lines.append("module i_decoder (")
    lines.append("    input  logic [63:0] instr,")

    # Opcode is special-cased (always lives in [4:0])
    lines.append("    output logic [4:0]  opcode,")

    port_decls = []
    for port, width in isa_spec.RTL_PORTS.items():
        port_decls.append(_port_decl(port, width))
    lines.append(",\n".join(port_decls))
    lines.append(");")
    lines.append("")
    lines.append("    always_comb begin")
    lines.append("        opcode = instr[4:0];")
    lines.append("")
    lines.append("        // Defaults — every output deassserted unless an opcode case drives it")
    for port in isa_spec.RTL_PORTS:
        lines.append(f"        {port} = 0;")
    lines.append("")
    lines.append("        case (opcode)")

    for op in isa_spec.OPCODES:
        if op.name == "NOP":
            lines.append(f"            5'h{op.value:02X}: begin // {op.name}")
            lines.append("            end")
            lines.append("")
            continue
        lines.append(f"            5'h{op.value:02X}: begin // {op.name} — {op.description}")
        # Sort fields by descending lo so the assignments in the case-arm
        # read top-down across the instruction word (matches how a human
        # eyeballs bit layouts).
        for f in sorted(op.fields, key=lambda x: -x.lo):
            if f.port is None:
                continue
            lines.append(_emit_field_assignment(f))
        lines.append("            end")
        lines.append("")

    lines.append("            default: begin")
    lines.append("            end")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", default=str(DEFAULT_OUTPUT),
                    help=f"Output path (default: {DEFAULT_OUTPUT})")
    ap.add_argument("--check", action="store_true",
                    help="Exit non-zero if the on-disk decoder differs from the spec")
    args = ap.parse_args()

    rendered = render()
    out_path = Path(args.output)

    if args.check:
        existing = out_path.read_text() if out_path.exists() else ""
        if existing != rendered:
            print(f"ERROR: {out_path} is stale relative to compiler/isa_spec.py.",
                  file=sys.stderr)
            print("Run: python tools/generate_i_decoder.py", file=sys.stderr)
            sys.exit(1)
        print(f"{out_path} is up to date with isa_spec.")
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered)
    print(f"Wrote {out_path} ({len(rendered)} bytes, {len(isa_spec.OPCODES)} opcodes)")


if __name__ == "__main__":
    main()
